### ISSUE TITLE
Cloudflare Apps discontinued

### ISSUE THREAD

**Issue by RChutchev** [Logflare/cloudflare-app#14]
Hi, I received an email from Cloudflare about Apps sunset soon.
According to the official Cloudflare Apps page, "Cloudflare Apps are deprecated and will be sunset in the near future. We will be creating a new Apps experience. If you’re interested, leave us feedback and sign up _LINK_" 

However, I wanna continue to use Logflare and start to use Logflare for a new domain.
Cloudflare blocked any possible ways to add a new application for existing and new zones.
I tried to install a new app via the link but after login and installation, i'm getting an error.
![Screenshot 2024-02-17 at 4 55 27 AM](https://github.com/Logflare/cloudflare-app/assets/11131666/b1e77bf9-bc7a-4a56-8183-3a2308938c75)
![Screenshot 2024-02-17 at 4 52 58 AM](https://github.com/Logflare/cloudflare-app/assets/11131666/f5d20380-7338-4173-8eeb-d51d587af571)

Maybe, can you offer Cloudflare users a workaround for bypassing Cf Apps? 
I mean instructions on how to create a "Cloudflare worker" and set up a connection with Logflare without a "Logflare app" b/c CF Apps will stop working soon for existing users too.

**Comment by RChutchev** [comment]
According to your repo Cf Worker is publicly available here: https://github.com/Logflare/cloudflare-app/blob/master/workers/worker.js
I'll try to configure/set Worker manually today, but it may be hard for some users.

That's maybe a real workaround, but i didn't find any mentions of that on the Logflare site.
Can u please update the website and provide instructions on how to configure a Worker to work with Logflare?

**Comment by EvelynOctavia** [comment]
Any progress, by the way? i tried to use a worker code from [this gist](https://gist.github.com/chasers/c7a220e91820a1084b27fcfdb18ad6bd), and i can see log going in when doing a GET request to my worker URL, but not when visiting my site. Hope you or others find a solution soon.
