### ISSUE TITLE
Not able to fetch content length

### ISSUE THREAD

**Issue by DawnImpulse** [Logflare/cloudflare-app#8]
Identified issue on line 25 of the worker/worker.js 
content length is misspelled.

**Comment by chasers** [comment]
Rad, fixed thanks!!  It will take a few days to get this updated in the Cloudflare App store.  

In the meantime, this is available in the log event metadata as `response.headers.content_length`.

**Comment by chasers** [comment]
@DawnImpulse update is live in the app store!

**Comment by DawnImpulse** [comment]
Thats great 👌
